### ISSUE TITLE
Encoding issues

### ISSUE THREAD

**Issue by antuki** [hrbrmstr/msgxtractr#1]
Hello ! 

Thank you for this small and nice package. 

Unfortunately I cannot run the read_msg fonction on my computer. I tried to run the README example and the error is the following : 

**Error in iconv(msg$body, from = "UTF-7") : 
  unsupported conversion from 'UTF-7' to '' in codepage 1252**

It may be because UTF-7 is not in my "iconvlist()". I'm working on windows 10. 

And as I said on twitter : I cannot read some of my e-mails with you example given here : http://rpubs.com/hrbrmstr/extractmsg . My R session is aborted each time I'm trying "msg$body". But most of the other emails are not problematic.

I think it may be another encoding issue in reticulate as I saw here : https://github.com/rstudio/reticulate/issues/90#issuecomment-324415365 . Because all the emails which fail have some special characters inside (from russia...). 

If you find any solution, i would be interested ! 

Thanks, 

Kim

**Comment by hrbrmstr** [comment]
Greetings!

Give it another go. I moved it to C++ (i.e. no python dep) and tested on macOS, Linux and Windows.

**Comment by antuki** [comment]
Indeed, no more encoding issues
