### ISSUE TITLE
Change default for file names in save_attachment()

### ISSUE THREAD

**Issue by marcelbaumgartner** [hrbrmstr/msgxtractr#5]
Hello. Thanks for this great package. Helped me a lot. What about changing the default for the file name in the save_attachment() function? I got confused for some time, because I "only" received the short name. Only by looking at the msg structure and the availabilty of "long_filename", I saw the solution. Why don't put this as an option into save_attachment() ? Thanks!

**Comment by hrbrmstr** [comment]
Smashing idea! #ty
