### ISSUE TITLE
Couldn't install

### ISSUE THREAD

**Issue by cstubbsphd** [hrbrmstr/msgxtractr#6]
I wasn't able to install this on a Win 7 x64 machine.  There were lots of warnings and errors, but I'm not sure what to make of them.  See below:

In R CMD INSTALL
"C:/PROGRA~1/R/R-34~1.3/bin/x64/R" --no-site-file --no-environ --no-save --no-restore  \
  --quiet CMD INSTALL  \
  "C:/Users/cstubbs/AppData/Local/Temp/Rtmpuaxv8o/devtools3048369d2c1a/hrbrmstr-msgxtractr-6769a39"  \
  --library="C:/Users/cstubbs/Documents/R/win-library/3.4" --install-tests 

* installing *source* package 'msgxtractr' ...
** libs

*** arch - i386
c:/Rtools/mingw_32/bin/g++  -std=gnu++11 -I"C:/PROGRA~1/R/R-34~1.3/include" -DNDEBUG  -I"C:/Users/cstubbs/Documents/R/win-library/3.4/Rcpp/include"        -O2 -Wall  -mtune=generic -c RcppExports.cpp -o RcppExports.o
c:/Rtools/mingw_32/bin/gcc  -I"C:/PROGRA~1/R/R-34~1.3/include" -DNDEBUG  -I"C:/Users/cstubbs/Documents/R/win-library/3.4/Rcpp/include"        -O3 -Wall  -std=gnu99 -mtune=generic -c alloc.c -o alloc.o
c:/Rtools/mingw_32/bin/gcc  -I"C:/PROGRA~1/R/R-34~1.3/include" -DNDEBUG  -I"C:/Users/cstubbs/Documents/R/win-library/3.4/Rcpp/include"        -O3 -Wall  -std=gnu99 -mtune=generic -c attr.c -o attr.o
attr.c: In function 'attr_dump':
attr.c:163:2: warning: implicit declaration of function 'strncpy' [-Wimplicit-function-declaration]
  strncpy (buf, (char*)attr->buf, attr->len);
  ^
attr.c:163:2: warning: incompatible implicit declaration of built-in function 'strncpy'
c:/Rtools/mingw_32/bin/gcc  -I"C:/PROGRA~1/R/R-34~1.3/include" -DNDEBUG  -I"C:/Users/cstubbs/Documents/R/win-library/3.4/Rcpp/include"        -O3 -Wall  -std=gnu99 -mtune=generic -c date.c -o date.o
c:/Rtools/mingw_32/bin/gcc  -I"C:/PROGRA~1/R/R-34~1.3/include" -DNDEBUG  -I"C:/Users/cstubbs/Documents/R/win-library/3.4/Rcpp/include"        -O3 -Wall  -std=gnu99 -mtune=generic -c debug.c -o debug.o
c:/Rtools/mingw_32/bin/gcc  -I"C:/PROGRA~1/R/R-34~1.3/include" -DNDEBUG  -I"C:/Users/cstubbs/Documents/R/win-library/3.4/Rcpp/include"        -O3 -Wall  -std=gnu99 -mtune=generic -c file.c -o file.o
file.c: In function 'file_write':
file.c:73:2: warning: implicit declaration of function 'strdup' [-Wimplicit-function-declaration]
  file->name = strdup( TNEF_DEFAULT_FILENAME );
  ^
file.c:73:15: warning: incompatible implicit declaration of built-in function 'strdup'
  file->name = strdup( TNEF_DEFAULT_FILENAME );
               ^
file.c:83:19: warning: incompatible implicit declaration of built-in function 'strdup'
      file->path = strdup( TNEF_DEFAULT_FILENAME );
                   ^
file.c:92:9: warning: incompatible implicit declaration of built-in function 'strdup'
  path = strdup( TNEF_DEFAULT_FILENAME );
         ^
file.c: In function 'file_add_mapi_attrs':
file.c:180:16: warning: incompatible implicit declaration of built-in function 'strdup'
   file->name = strdup( (char*)a->values[0].data.buf );
                ^
file.c: In function 'file_add_attr':
file.c:235:15: warning: incompatible implicit declaration of built-in function 'strdup'
  file->name = strdup( (char*)attr->buf );
               ^
c:/Rtools/mingw_32/bin/gcc  -I"C:/PROGRA~1/R/R-34~1.3/include" -DNDEBUG  -I"C:/Users/cstubbs/Documents/R/win-library/3.4/Rcpp/include"        -O3 -Wall  -std=gnu99 -mtune=generic -c mapi_attr.c -o mapi_attr.o
c:/Rtools/mingw_32/bin/gcc  -I"C:/PROGRA~1/R/R-34~1.3/include" -DNDEBUG  -I"C:/Users/cstubbs/Documents/R/win-library/3.4/Rcpp/include"        -O3 -Wall  -std=gnu99 -mtune=generic -c mapi_names.c -o mapi_names.o
c:/Rtools/mingw_32/bin/gcc  -I"C:/PROGRA~1/R/R-34~1.3/include" -DNDEBUG  -I"C:/Users/cstubbs/Documents/R/win-library/3.4/Rcpp/include"        -O3 -Wall  -std=gnu99 -mtune=generic -c mapi_types.c -o mapi_types.o
c:/Rtools/mingw_32/bin/gcc  -I"C:/PROGRA~1/R/R-34~1.3/include" -DNDEBUG  -I"C:/Users/cstubbs/Documents/R/win-library/3.4/Rcpp/include"        -O3 -Wall  -std=gnu99 -mtune=generic -c options.c -o options.o
c:/Rtools/mingw_32/bin/gcc  -I"C:/PROGRA~1/R/R-34~1.3/include" -DNDEBUG  -I"C:/Users/cstubbs/Documents/R/win-library/3.4/Rcpp/include"        -O3 -Wall  -std=gnu99 -mtune=generic -c path.c -o path.o
path.c: In function 'could_be_a_windows_path':
path.c:148:5: warning: implicit declaration of function 'rindex' [-Wimplicit-function-declaration]
     up = rindex( fname, '\\' );
     ^
path.c:148:10: warning: incompatible implicit declaration of built-in function 'rindex'
     up = rindex( fname, '\\' );
          ^
path.c:164:2: warning: implicit declaration of function 'index' [-Wimplicit-function-declaration]
  if ( index( fname, (int)*up ) )
  ^
path.c:164:7: warning: incompatible implicit declaration of built-in function 'index'
  if ( index( fname, (int)*up ) )
       ^
path.c: In function 'munge_fname':
path.c:328:13: warning: incompatible implicit declaration of built-in function 'rindex'
      base = rindex( dir, (int)'\\' );
             ^
c:/Rtools/mingw_32/bin/g++  -std=gnu++11 -I"C:/PROGRA~1/R/R-34~1.3/include" -DNDEBUG  -I"C:/Users/cstubbs/Documents/R/win-library/3.4/Rcpp/include"        -O2 -Wall  -mtune=generic -c pole.cpp -o pole.o
pole.cpp: In member function 'void POLE::DirTree::load(unsigned char*, unsigned int)':
pole.cpp:670:14: warning: variable 'prefix' set but not used [-Wunused-but-set-variable]
     unsigned prefix = 32;
              ^
c:/Rtools/mingw_32/bin/g++  -std=gnu++11 -I"C:/PROGRA~1/R/R-34~1.3/include" -DNDEBUG  -I"C:/Users/cstubbs/Documents/R/win-library/3.4/Rcpp/include"        -O2 -Wall  -mtune=generic -c r_pole.cpp -o r_pole.o
In file included from r_pole.cpp:15:0:
util.h:36:8: error: 'uint32' does not name a type
 extern uint32 GETINT32(unsigned char*p);
        ^
util.h:37:8: error: 'uint16' does not name a type
 extern uint16 GETINT16(unsigned char*p);
        ^
util.h:38:8: error: 'uint8' does not name a type
 extern uint8 GETINT8(unsigned char*p);
        ^
util.h:41:8: error: 'uint32' does not name a type
 extern uint32 geti32(FILE *fp);
        ^
util.h:42:8: error: 'uint16' does not name a type
 extern uint16 geti16(FILE *fp);
        ^
util.h:43:8: error: 'uint8' does not name a type
 extern uint8 geti8(FILE *fp);
        ^
In file included from mapi_attr.h:35:0,
                 from rtf.h:32,
                 from r_pole.cpp:17:
mapi_types.h:30:19: warning: 'get_mapi_type_str' initialized and declared 'extern'
 get_mapi_type_str(uint16 d);
                   ^
mapi_types.h:30:19: error: 'uint16' was not declared in this scope
In file included from mapi_attr.h:36:0,
                 from rtf.h:32,
                 from r_pole.cpp:17:
mapi_names.h:440:19: warning: 'get_mapi_name_str' initialized and declared 'extern'
 get_mapi_name_str(uint16 d);
                   ^
mapi_names.h:440:19: error: 'uint16' was not declared in this scope
In file included from rtf.h:32:0,
                 from r_pole.cpp:17:
mapi_attr.h:43:5: error: 'uint32' does not name a type
     uint32 data1;
     ^
mapi_attr.h:44:5: error: 'uint16' does not name a type
     uint16 data2;
     ^
mapi_attr.h:45:5: error: 'uint16' does not name a type
     uint16 data3;
     ^
mapi_attr.h:46:5: error: 'uint8' does not name a type
     uint8 data4[8];
     ^
mapi_attr.h:55:2: error: 'uint16' does not name a type
  uint16 bytes2;
  ^
mapi_attr.h:56:2: error: 'uint32' does not name a type
  uint32 bytes4;
  ^
mapi_attr.h:57:2: error: 'uint32' does not name a type
  uint32 bytes8[2];
  ^
r_pole.cpp: In function 'Rcpp::RawVector decompress_rtf_data(unsigned char*, size_t, size_t)':
r_pole.cpp:92:16: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
     if ( cin+1 > lenc ) {
                ^
r_pole.cpp:107:20: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
         if ( cin+2 > lenc ){
                    ^
r_pole.cpp:125:24: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
         if ( cout+rlen > lenu ) {
                        ^
r_pole.cpp:142:20: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
         if ( cin+1 > lenc ) {
                    ^
r_pole.cpp:147:21: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
         if ( cout+1 > lenu ) {
                     ^
r_pole.cpp: In function 'Rcpp::RawVector decode_rtf(Rcpp::RawVector)':
r_pole.cpp:175:29: warning: unused variable 'rtf_uncompressed_magic' [-Wunused-variable]
   static const unsigned int rtf_uncompressed_magic = 0x414c454d;
                             ^
make: *** [r_pole.o] Error 1
Warning: running command 'make -f "Makevars" -f "C:/PROGRA~1/R/R-34~1.3/etc/i386/Makeconf" -f "C:/PROGRA~1/R/R-34~1.3/share/make/winshlib.mk" CXX='$(CXX11) $(CXX11STD)' CXXFLAGS='$(CXX11FLAGS)' CXXPICFLAGS='$(CXX11PICFLAGS)' SHLIB_LDFLAGS='$(SHLIB_CXX11LDFLAGS)' SHLIB_LD='$(SHLIB_CXX11LD)' SHLIB="msgxtractr.dll" OBJECTS="RcppExports.o alloc.o attr.o date.o debug.o file.o mapi_attr.o mapi_names.o mapi_types.o options.o path.o pole.o r_pole.o rtf.o tnef.o tnef_names.o tnef_types.o util.o write.o xstrdup.o"' had status 2
ERROR: compilation failed for package 'msgxtractr'
* removing 'C:/Users/cstubbs/Documents/R/win-library/3.4/msgxtractr'
In R CMD INSTALL
Installation failed: Command failed (1)

**Comment by tshurtz** [comment]
I also got a super long error message:

Downloading GitHub repo hrbrmstr/msgxtractr@master
from URL https://api.github.com/repos/hrbrmstr/msgxtractr/zipball/master
Installing msgxtractr
"C:/Users/TANNER~1.SHU/DOCUME~1/R/R-34~1.3/bin/i386/R" --no-site-file --no-environ --no-save --no-restore --quiet CMD  \
  INSTALL "C:/Users/Tanner.Shurtz/AppData/Local/Temp/RtmpEf1RRv/devtools29a05eca56f5/hrbrmstr-msgxtractr-6769a39"  \
  --library="C:/Users/Tanner.Shurtz/Documents/R/R-3.4.3/library" --install-tests 

* installing *source* package 'msgxtractr' ...
** libs

*** arch - i386
c:/Rtools/mingw_32/bin/g++  -std=gnu++11 -I"C:/Users/TANNER~1.SHU/DOCUME~1/R/R-34~1.3/include" -DNDEBUG  -I"C:/Users/Tanner.Shurtz/Documents/R/R-3.4.3/library/Rcpp/include"        -O2 -Wall  -mtune=generic -c RcppExports.cpp -o RcppExports.o
c:/Rtools/mingw_32/bin/gcc  -I"C:/Users/TANNER~1.SHU/DOCUME~1/R/R-34~1.3/include" -DNDEBUG  -I"C:/Users/Tanner.Shurtz/Documents/R/R-3.4.3/library/Rcpp/include"        -O3 -Wall  -std=gnu99 -mtune=generic -c alloc.c -o alloc.o
c:/Rtools/mingw_32/bin/gcc  -I"C:/Users/TANNER~1.SHU/DOCUME~1/R/R-34~1.3/include" -DNDEBUG  -I"C:/Users/Tanner.Shurtz/Documents/R/R-3.4.3/library/Rcpp/include"        -O3 -Wall  -std=gnu99 -mtune=generic -c attr.c -o attr.o
attr.c: In function 'attr_dump':
attr.c:163:2: warning: implicit declaration of function 'strncpy' [-Wimplicit-function-declaration]
  strncpy (buf, (char*)attr->buf, attr->len);
  ^
attr.c:163:2: warning: incompatible implicit declaration of built-in function 'strncpy'
c:/Rtools/mingw_32/bin/gcc  -I"C:/Users/TANNER~1.SHU/DOCUME~1/R/R-34~1.3/include" -DNDEBUG  -I"C:/Users/Tanner.Shurtz/Documents/R/R-3.4.3/library/Rcpp/include"        -O3 -Wall  -std=gnu99 -mtune=generic -c date.c -o date.o
c:/Rtools/mingw_32/bin/gcc  -I"C:/Users/TANNER~1.SHU/DOCUME~1/R/R-34~1.3/include" -DNDEBUG  -I"C:/Users/Tanner.Shurtz/Documents/R/R-3.4.3/library/Rcpp/include"        -O3 -Wall  -std=gnu99 -mtune=generic -c debug.c -o debug.o
c:/Rtools/mingw_32/bin/gcc  -I"C:/Users/TANNER~1.SHU/DOCUME~1/R/R-34~1.3/include" -DNDEBUG  -I"C:/Users/Tanner.Shurtz/Documents/R/R-3.4.3/library/Rcpp/include"        -O3 -Wall  -std=gnu99 -mtune=generic -c file.c -o file.o
file.c: In function 'file_write':
file.c:73:2: warning: implicit declaration of function 'strdup' [-Wimplicit-function-declaration]
  file->name = strdup( TNEF_DEFAULT_FILENAME );
  ^
file.c:73:15: warning: incompatible implicit declaration of built-in function 'strdup'
  file->name = strdup( TNEF_DEFAULT_FILENAME );
               ^
file.c:83:19: warning: incompatible implicit declaration of built-in function 'strdup'
      file->path = strdup( TNEF_DEFAULT_FILENAME );
                   ^
file.c:92:9: warning: incompatible implicit declaration of built-in function 'strdup'
  path = strdup( TNEF_DEFAULT_FILENAME );
         ^
file.c: In function 'file_add_mapi_attrs':
file.c:180:16: warning: incompatible implicit declaration of built-in function 'strdup'
   file->name = strdup( (char*)a->values[0].data.buf );
                ^
file.c: In function 'file_add_attr':
file.c:235:15: warning: incompatible implicit declaration of built-in function 'strdup'
  file->name = strdup( (char*)attr->buf );
               ^
c:/Rtools/mingw_32/bin/gcc  -I"C:/Users/TANNER~1.SHU/DOCUME~1/R/R-34~1.3/include" -DNDEBUG  -I"C:/Users/Tanner.Shurtz/Documents/R/R-3.4.3/library/Rcpp/include"        -O3 -Wall  -std=gnu99 -mtune=generic -c mapi_attr.c -o mapi_attr.o
c:/Rtools/mingw_32/bin/gcc  -I"C:/Users/TANNER~1.SHU/DOCUME~1/R/R-34~1.3/include" -DNDEBUG  -I"C:/Users/Tanner.Shurtz/Documents/R/R-3.4.3/library/Rcpp/include"        -O3 -Wall  -std=gnu99 -mtune=generic -c mapi_names.c -o mapi_names.o
c:/Rtools/mingw_32/bin/gcc  -I"C:/Users/TANNER~1.SHU/DOCUME~1/R/R-34~1.3/include" -DNDEBUG  -I"C:/Users/Tanner.Shurtz/Documents/R/R-3.4.3/library/Rcpp/include"        -O3 -Wall  -std=gnu99 -mtune=generic -c mapi_types.c -o mapi_types.o
c:/Rtools/mingw_32/bin/gcc  -I"C:/Users/TANNER~1.SHU/DOCUME~1/R/R-34~1.3/include" -DNDEBUG  -I"C:/Users/Tanner.Shurtz/Documents/R/R-3.4.3/library/Rcpp/include"        -O3 -Wall  -std=gnu99 -mtune=generic -c options.c -o options.o
c:/Rtools/mingw_32/bin/gcc  -I"C:/Users/TANNER~1.SHU/DOCUME~1/R/R-34~1.3/include" -DNDEBUG  -I"C:/Users/Tanner.Shurtz/Documents/R/R-3.4.3/library/Rcpp/include"        -O3 -Wall  -std=gnu99 -mtune=generic -c path.c -o path.o
path.c: In function 'could_be_a_windows_path':
path.c:148:5: warning: implicit declaration of function 'rindex' [-Wimplicit-function-declaration]
     up = rindex( fname, '\\' );
     ^
path.c:148:10: warning: incompatible implicit declaration of built-in function 'rindex'
     up = rindex( fname, '\\' );
          ^
path.c:164:2: warning: implicit declaration of function 'index' [-Wimplicit-function-declaration]
  if ( index( fname, (int)*up ) )
  ^
path.c:164:7: warning: incompatible implicit declaration of built-in function 'index'
  if ( index( fname, (int)*up ) )
       ^
path.c: In function 'munge_fname':
path.c:328:13: warning: incompatible implicit declaration of built-in function 'rindex'
      base = rindex( dir, (int)'\\' );
             ^
c:/Rtools/mingw_32/bin/g++  -std=gnu++11 -I"C:/Users/TANNER~1.SHU/DOCUME~1/R/R-34~1.3/include" -DNDEBUG  -I"C:/Users/Tanner.Shurtz/Documents/R/R-3.4.3/library/Rcpp/include"        -O2 -Wall  -mtune=generic -c pole.cpp -o pole.o
pole.cpp: In member function 'void POLE::DirTree::load(unsigned char*, unsigned int)':
pole.cpp:670:14: warning: variable 'prefix' set but not used [-Wunused-but-set-variable]
     unsigned prefix = 32;
              ^
c:/Rtools/mingw_32/bin/g++  -std=gnu++11 -I"C:/Users/TANNER~1.SHU/DOCUME~1/R/R-34~1.3/include" -DNDEBUG  -I"C:/Users/Tanner.Shurtz/Documents/R/R-3.4.3/library/Rcpp/include"        -O2 -Wall  -mtune=generic -c r_pole.cpp -o r_pole.o
In file included from r_pole.cpp:15:0:
util.h:36:8: error: 'uint32' does not name a type
 extern uint32 GETINT32(unsigned char*p);
        ^
util.h:37:8: error: 'uint16' does not name a type
 extern uint16 GETINT16(unsigned char*p);
        ^
util.h:38:8: error: 'uint8' does not name a type
 extern uint8 GETINT8(unsigned char*p);
        ^
util.h:41:8: error: 'uint32' does not name a type
 extern uint32 geti32(FILE *fp);
        ^
util.h:42:8: error: 'uint16' does not name a type
 extern uint16 geti16(FILE *fp);
        ^
util.h:43:8: error: 'uint8' does not name a type
 extern uint8 geti8(FILE *fp);
        ^
In file included from mapi_attr.h:35:0,
                 from rtf.h:32,
                 from r_pole.cpp:17:
mapi_types.h:30:19: warning: 'get_mapi_type_str' initialized and declared 'extern'
 get_mapi_type_str(uint16 d);
                   ^
mapi_types.h:30:19: error: 'uint16' was not declared in this scope
In file included from mapi_attr.h:36:0,
                 from rtf.h:32,
                 from r_pole.cpp:17:
mapi_names.h:440:19: warning: 'get_mapi_name_str' initialized and declared 'extern'
 get_mapi_name_str(uint16 d);
                   ^
mapi_names.h:440:19: error: 'uint16' was not declared in this scope
In file included from rtf.h:32:0,
                 from r_pole.cpp:17:
mapi_attr.h:43:5: error: 'uint32' does not name a type
     uint32 data1;
     ^
mapi_attr.h:44:5: error: 'uint16' does not name a type
     uint16 data2;
     ^
mapi_attr.h:45:5: error: 'uint16' does not name a type
     uint16 data3;
     ^
mapi_attr.h:46:5: error: 'uint8' does not name a type
     uint8 data4[8];
     ^
mapi_attr.h:55:2: error: 'uint16' does not name a type
  uint16 bytes2;
  ^
mapi_attr.h:56:2: error: 'uint32' does not name a type
  uint32 bytes4;
  ^
mapi_attr.h:57:2: error: 'uint32' does not name a type
  uint32 bytes8[2];
  ^
r_pole.cpp: In function 'Rcpp::RawVector decompress_rtf_data(unsigned char*, size_t, size_t)':
r_pole.cpp:92:16: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
     if ( cin+1 > lenc ) {
                ^
r_pole.cpp:107:20: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
         if ( cin+2 > lenc ){
                    ^
r_pole.cpp:125:24: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
         if ( cout+rlen > lenu ) {
                        ^
r_pole.cpp:142:20: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
         if ( cin+1 > lenc ) {
                    ^
r_pole.cpp:147:21: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
         if ( cout+1 > lenu ) {
                     ^
r_pole.cpp: In function 'Rcpp::RawVector decode_rtf(Rcpp::RawVector)':
r_pole.cpp:175:29: warning: unused variable 'rtf_uncompressed_magic' [-Wunused-variable]
   static const unsigned int rtf_uncompressed_magic = 0x414c454d;
                             ^
make: *** [r_pole.o] Error 1
Warning: running command 'make -f "Makevars" -f "C:/Users/TANNER~1.SHU/DOCUME~1/R/R-34~1.3/etc/i386/Makeconf" -f "C:/Users/TANNER~1.SHU/DOCUME~1/R/R-34~1.3/share/make/winshlib.mk" CXX='$(CXX11) $(CXX11STD)' CXXFLAGS='$(CXX11FLAGS)' CXXPICFLAGS='$(CXX11PICFLAGS)' SHLIB_LDFLAGS='$(SHLIB_CXX11LDFLAGS)' SHLIB_LD='$(SHLIB_CXX11LD)' SHLIB="msgxtractr.dll" OBJECTS="RcppExports.o alloc.o attr.o date.o debug.o file.o mapi_attr.o mapi_names.o mapi_types.o options.o path.o pole.o r_pole.o rtf.o tnef.o tnef_names.o tnef_types.o util.o write.o xstrdup.o"' had status 2
ERROR: compilation failed for package 'msgxtractr'
* removing 'C:/Users/Tanner.Shurtz/Documents/R/R-3.4.3/library/msgxtractr'
In R CMD INSTALL
Installation failed: Command failed (1)

**Comment by hrbrmstr** [comment]
Give it a go now. I removed some experimental bits and tested it on a Windows VM and it works.

**Comment by cstubbsphd** [comment]
Yes, it works now.  Thanks!

**Comment by Gupta-Vipul** [comment]
hi @hrbrmstr, I am getting the same error in todays date... following are the details
R version: 3.4.4
RTools: 3.4
OS: Windows 10

**Comment by aschinch** [comment]
I am facing the same issue now also. Please let me know if it is fixed. Trying to install through
devtools::install_github("hrbrmstr/msgxtractr")

**Comment by hrbrmstr** [comment]
give it a go again, folks. I think i managed to tweak whatever changed from the prior compilation behavior.
