### ISSUE TITLE
Error when installing on Windows (R 3.4.1)

### ISSUE THREAD

**Issue by marcelbaumgartner** [hrbrmstr/msgxtractr#7]
[Error message install.txt](https://github.com/hrbrmstr/msgxtractr/files/1824103/Error.message.install.txt)
Hi, i am not able to install anymore your library. Error message, traceback and sessioninfo attached.

**Comment by hrbrmstr** [comment]
thx. I likely need to stub in some functions on Windows.

**Comment by barrypegado** [comment]
@marcelbaumgartner Where you able to install successfully?

**Comment by marcelbaumgartner** [comment]
Hello, still an error. See below:
> devtools::install_github("hrbrmstr/msgxtractr")
Downloading GitHub repo hrbrmstr/msgxtractr@master
from URL https://api.github.com/repos/hrbrmstr/msgxtractr/zipball/master
Installing msgxtractr
"C:/R/R-34~1.1/bin/x64/R" --no-site-file --no-environ --no-save --no-restore --quiet CMD  \
  INSTALL  \
  "C:/Users/mbaumga/AppData/Local/Temp/RtmpApXSf5/devtools2c5034eb43c1/hrbrmstr-msgxtractr-6769a39"  \
  --library="C:/R/R-3.4.1/library" --install-tests 

* installing *source* package 'msgxtractr' ...
** libs
C:/RBuildTools/3.4/mingw_64/bin/g++  -std=gnu++11 -I"C:/R/R-34~1.1/include" -DNDEBUG  -I"C:/R/R-3.4.1/library/Rcpp/include"   -I"d:/Compiler/gcc-4.9.3/local330/include"     -O2 -Wall  -mtune=core2 -c RcppExports.cpp -o RcppExports.o
C:/RBuildTools/3.4/mingw_64/bin/gcc  -I"C:/R/R-34~1.1/include" -DNDEBUG  -I"C:/R/R-3.4.1/library/Rcpp/include"   -I"d:/Compiler/gcc-4.9.3/local330/include"     -O2 -Wall  -std=gnu99 -mtune=core2 -c alloc.c -o alloc.o
C:/RBuildTools/3.4/mingw_64/bin/gcc  -I"C:/R/R-34~1.1/include" -DNDEBUG  -I"C:/R/R-3.4.1/library/Rcpp/include"   -I"d:/Compiler/gcc-4.9.3/local330/include"     -O2 -Wall  -std=gnu99 -mtune=core2 -c attr.c -o attr.o
attr.c: In function 'attr_dump':
attr.c:163:2: warning: implicit declaration of function 'strncpy' [-Wimplicit-function-declaration]
  strncpy (buf, (char*)attr->buf, attr->len);
  ^
attr.c:163:2: warning: incompatible implicit declaration of built-in function 'strncpy'
C:/RBuildTools/3.4/mingw_64/bin/gcc  -I"C:/R/R-34~1.1/include" -DNDEBUG  -I"C:/R/R-3.4.1/library/Rcpp/include"   -I"d:/Compiler/gcc-4.9.3/local330/include"     -O2 -Wall  -std=gnu99 -mtune=core2 -c date.c -o date.o
C:/RBuildTools/3.4/mingw_64/bin/gcc  -I"C:/R/R-34~1.1/include" -DNDEBUG  -I"C:/R/R-3.4.1/library/Rcpp/include"   -I"d:/Compiler/gcc-4.9.3/local330/include"     -O2 -Wall  -std=gnu99 -mtune=core2 -c debug.c -o debug.o
C:/RBuildTools/3.4/mingw_64/bin/gcc  -I"C:/R/R-34~1.1/include" -DNDEBUG  -I"C:/R/R-3.4.1/library/Rcpp/include"   -I"d:/Compiler/gcc-4.9.3/local330/include"     -O2 -Wall  -std=gnu99 -mtune=core2 -c file.c -o file.o
file.c: In function 'file_write':
file.c:73:2: warning: implicit declaration of function 'strdup' [-Wimplicit-function-declaration]
  file->name = strdup( TNEF_DEFAULT_FILENAME );
  ^
file.c:73:15: warning: incompatible implicit declaration of built-in function 'strdup'
  file->name = strdup( TNEF_DEFAULT_FILENAME );
               ^
file.c:83:19: warning: incompatible implicit declaration of built-in function 'strdup'
      file->path = strdup( TNEF_DEFAULT_FILENAME );
                   ^
file.c:92:9: warning: incompatible implicit declaration of built-in function 'strdup'
  path = strdup( TNEF_DEFAULT_FILENAME );
         ^
file.c: In function 'file_add_mapi_attrs':
file.c:180:16: warning: incompatible implicit declaration of built-in function 'strdup'
   file->name = strdup( (char*)a->values[0].data.buf );
                ^
file.c: In function 'file_add_attr':
file.c:235:15: warning: incompatible implicit declaration of built-in function 'strdup'
  file->name = strdup( (char*)attr->buf );
               ^
C:/RBuildTools/3.4/mingw_64/bin/gcc  -I"C:/R/R-34~1.1/include" -DNDEBUG  -I"C:/R/R-3.4.1/library/Rcpp/include"   -I"d:/Compiler/gcc-4.9.3/local330/include"     -O2 -Wall  -std=gnu99 -mtune=core2 -c mapi_attr.c -o mapi_attr.o
C:/RBuildTools/3.4/mingw_64/bin/gcc  -I"C:/R/R-34~1.1/include" -DNDEBUG  -I"C:/R/R-3.4.1/library/Rcpp/include"   -I"d:/Compiler/gcc-4.9.3/local330/include"     -O2 -Wall  -std=gnu99 -mtune=core2 -c mapi_names.c -o mapi_names.o
C:/RBuildTools/3.4/mingw_64/bin/gcc  -I"C:/R/R-34~1.1/include" -DNDEBUG  -I"C:/R/R-3.4.1/library/Rcpp/include"   -I"d:/Compiler/gcc-4.9.3/local330/include"     -O2 -Wall  -std=gnu99 -mtune=core2 -c mapi_types.c -o mapi_types.o
C:/RBuildTools/3.4/mingw_64/bin/gcc  -I"C:/R/R-34~1.1/include" -DNDEBUG  -I"C:/R/R-3.4.1/library/Rcpp/include"   -I"d:/Compiler/gcc-4.9.3/local330/include"     -O2 -Wall  -std=gnu99 -mtune=core2 -c options.c -o options.o
C:/RBuildTools/3.4/mingw_64/bin/gcc  -I"C:/R/R-34~1.1/include" -DNDEBUG  -I"C:/R/R-3.4.1/library/Rcpp/include"   -I"d:/Compiler/gcc-4.9.3/local330/include"     -O2 -Wall  -std=gnu99 -mtune=core2 -c path.c -o path.o
path.c: In function 'could_be_a_windows_path':
path.c:148:5: warning: implicit declaration of function 'rindex' [-Wimplicit-function-declaration]
     up = rindex( fname, '\\' );
     ^
path.c:148:10: warning: incompatible implicit declaration of built-in function 'rindex'
     up = rindex( fname, '\\' );
          ^
path.c:164:2: warning: implicit declaration of function 'index' [-Wimplicit-function-declaration]
  if ( index( fname, (int)*up ) )
  ^
path.c:164:7: warning: incompatible implicit declaration of built-in function 'index'
  if ( index( fname, (int)*up ) )
       ^
path.c: In function 'munge_fname':
path.c:328:13: warning: incompatible implicit declaration of built-in function 'rindex'
      base = rindex( dir, (int)'\\' );
             ^
C:/RBuildTools/3.4/mingw_64/bin/g++  -std=gnu++11 -I"C:/R/R-34~1.1/include" -DNDEBUG  -I"C:/R/R-3.4.1/library/Rcpp/include"   -I"d:/Compiler/gcc-4.9.3/local330/include"     -O2 -Wall  -mtune=core2 -c pole.cpp -o pole.o
pole.cpp: In member function 'void POLE::DirTree::load(unsigned char*, unsigned int)':
pole.cpp:670:14: warning: variable 'prefix' set but not used [-Wunused-but-set-variable]
     unsigned prefix = 32;
              ^
C:/RBuildTools/3.4/mingw_64/bin/g++  -std=gnu++11 -I"C:/R/R-34~1.1/include" -DNDEBUG  -I"C:/R/R-3.4.1/library/Rcpp/include"   -I"d:/Compiler/gcc-4.9.3/local330/include"     -O2 -Wall  -mtune=core2 -c r_pole.cpp -o r_pole.o
In file included from r_pole.cpp:15:0:
util.h:36:8: error: 'uint32' does not name a type
 extern uint32 GETINT32(unsigned char*p);
        ^
util.h:37:8: error: 'uint16' does not name a type
 extern uint16 GETINT16(unsigned char*p);
        ^
util.h:38:8: error: 'uint8' does not name a type
 extern uint8 GETINT8(unsigned char*p);
        ^
util.h:41:8: error: 'uint32' does not name a type
 extern uint32 geti32(FILE *fp);
        ^
util.h:42:8: error: 'uint16' does not name a type
 extern uint16 geti16(FILE *fp);
        ^
util.h:43:8: error: 'uint8' does not name a type
 extern uint8 geti8(FILE *fp);
        ^
In file included from mapi_attr.h:35:0,
                 from rtf.h:32,
                 from r_pole.cpp:17:
mapi_types.h:30:19: warning: 'get_mapi_type_str' initialized and declared 'extern'
 get_mapi_type_str(uint16 d);
                   ^
mapi_types.h:30:19: error: 'uint16' was not declared in this scope
In file included from mapi_attr.h:36:0,
                 from rtf.h:32,
                 from r_pole.cpp:17:
mapi_names.h:440:19: warning: 'get_mapi_name_str' initialized and declared 'extern'
 get_mapi_name_str(uint16 d);
                   ^
mapi_names.h:440:19: error: 'uint16' was not declared in this scope
In file included from rtf.h:32:0,
                 from r_pole.cpp:17:
mapi_attr.h:43:5: error: 'uint32' does not name a type
     uint32 data1;
     ^
mapi_attr.h:44:5: error: 'uint16' does not name a type
     uint16 data2;
     ^
mapi_attr.h:45:5: error: 'uint16' does not name a type
     uint16 data3;
     ^
mapi_attr.h:46:5: error: 'uint8' does not name a type
     uint8 data4[8];
     ^
mapi_attr.h:55:2: error: 'uint16' does not name a type
  uint16 bytes2;
  ^
mapi_attr.h:56:2: error: 'uint32' does not name a type
  uint32 bytes4;
  ^
mapi_attr.h:57:2: error: 'uint32' does not name a type
  uint32 bytes8[2];
  ^
r_pole.cpp: In function 'Rcpp::RawVector decompress_rtf_data(unsigned char*, size_t, size_t)':
r_pole.cpp:92:16: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
     if ( cin+1 > lenc ) {
                ^
r_pole.cpp:107:20: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
         if ( cin+2 > lenc ){
                    ^
r_pole.cpp:125:24: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
         if ( cout+rlen > lenu ) {
                        ^
r_pole.cpp:142:20: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
         if ( cin+1 > lenc ) {
                    ^
r_pole.cpp:147:21: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
         if ( cout+1 > lenu ) {
                     ^
r_pole.cpp: In function 'Rcpp::RawVector decode_rtf(Rcpp::RawVector)':
r_pole.cpp:175:29: warning: unused variable 'rtf_uncompressed_magic' [-Wunused-variable]
   static const unsigned int rtf_uncompressed_magic = 0x414c454d;
                             ^
make: *** [r_pole.o] Error 1
Warning: l'exécution de la commande 'make -f "Makevars" -f "C:/R/R-34~1.1/etc/x64/Makeconf" -f "C:/R/R-34~1.1/share/make/winshlib.mk" CXX='$(CXX11) $(CXX11STD)' CXXFLAGS='$(CXX11FLAGS)' CXXPICFLAGS='$(CXX11PICFLAGS)' SHLIB_LDFLAGS='$(SHLIB_CXX11LDFLAGS)' SHLIB_LD='$(SHLIB_CXX11LD)' SHLIB="msgxtractr.dll" WIN=64 TCLBIN=64 OBJECTS="RcppExports.o alloc.o attr.o date.o debug.o file.o mapi_attr.o mapi_names.o mapi_types.o options.o path.o pole.o r_pole.o rtf.o tnef.o tnef_names.o tnef_types.o util.o write.o xstrdup.o"' renvoie un statut 2
ERROR: compilation failed for package 'msgxtractr'
* removing 'C:/R/R-3.4.1/library/msgxtractr'
Installation failed: Command failed (1)
> traceback()
Pas d'historique des fonctions appelées ('traceback') disponible 
> sessionInfo()
R version 3.4.1 (2017-06-30)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows >= 8 x64 (build 9200)

Matrix products: default

locale:
[1] LC_COLLATE=French_Switzerland.1252  LC_CTYPE=French_Switzerland.1252    LC_MONETARY=French_Switzerland.1252
[4] LC_NUMERIC=C                        LC_TIME=French_Switzerland.1252    

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] pander_0.6.1   bindrcpp_0.2.2 ggplot2_2.2.1  dplyr_0.7.4    readxl_1.0.0  

loaded via a namespace (and not attached):
 [1] Rcpp_0.12.16     cellranger_1.1.0 pillar_1.2.1     compiler_3.4.1   git2r_0.21.0     plyr_1.8.4       bindr_0.1.1     
 [8] tools_3.4.1      digest_0.6.15    evaluate_0.10.1  memoise_1.1.0    tibble_1.4.2     gtable_0.2.0     pkgconfig_2.0.1 
[15] rlang_0.2.0      curl_3.2         yaml_2.1.18      withr_2.1.2      stringr_1.3.0    httr_1.3.1       knitr_1.20      
[22] devtools_1.13.5  rprojroot_1.3-2  grid_3.4.1       glue_1.2.0       R6_2.2.2         rmarkdown_1.9    magrittr_1.5    
[29] scales_0.5.0     backports_1.1.2  htmltools_0.3.6  assertthat_0.2.0 colorspace_1.3-2 labeling_0.3     stringi_1.1.7   
[36] lazyeval_0.2.1   munsell_0.4.3   
>

**Comment by hrbrmstr** [comment]
Give it a go now. I removed some experimental code that was killing compilation on Windows and it worked on the Windows VM I finally updated and tested it on.

**Comment by marcelbaumgartner** [comment]
All okay now. Thanks! :)
